-- overview of customer shoping data
select * from customer_shoping limit 10 ;


-- What is the total revenue generated by male vs female customer ?
select gender,sum(purchase_amount_usd) as revenue
from customer_shoping 
group by gender;


-- Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount_usd
from customer_shoping
where discount_applied = "Yes"  and purchase_amount_usd > (select avg(purchase_amount_usd) from customer_shoping);



-- Which are the top 5 products with the highest average review rating ?
select item_purchased,round(avg(review_rating),2) as ratings
from customer_shoping
group by item_purchased
order by ratings desc
limit 5;


-- Compare the average purchase amounts between standard and express shipping.
select shipping_type,round(avg(purchase_amount_usd),2) as amount
from customer_shoping
where shipping_type in ("Express", "Standard")
group by shipping_type;


-- Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers ?
select subscription_status,
round(avg(purchase_amount_usd),2) as average_spend,
sum(purchase_amount_usd) as total_revenue
from customer_shoping
group by subscription_status;



-- Which 5 product has the highest percentage of purchases with discounts applied ?
select item_purchased,
round(100*sum(if(discount_applied = "Yes" ,1,0))/count(*),2)as purchase_rate
from customer_shoping
group by item_purchased
order by purchase_rate desc
limit 5;



-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with cte as(
select 
	customer_id,
	case 
		when previous_purchases=1 then "New"
		when previous_purchases between 2 and 10 then "Returning"
		else "Loyal"
	end as "loyality_review"
from customer_shoping
)

select loyality_review,count(customer_id) as counts
from cte
group by loyality_review;




-- What are the top 3 most purchased products within each category ?
with cte as (
select 
category,item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_ranks
from customer_shoping
group by category,item_purchased

)

select item_ranks,category,item_purchased,total_orders
from cte
where item_ranks <=3;




-- Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe ?
select subscription_status,count(customer_id) as repeat_buyers
from customer_shoping
where previous_purchases > 5 
group by subscription_status;




-- What is the revenue contribution of each age group ?
select age_group,round(avg(purchase_amount_usd),2) as revenue
from customer_shoping
group by age_group;

